import { readFile } from "node:fs/promises";
import { extname } from "node:path";
import {
  createAssetPath,
  createDefaultProject,
  type StudioDocumentPackage,
  type GraphForgeSourceArtifact,
  type OgProject,
  type SourceArtifactKind,
  type SourceArtifactOrigin
} from "@graphforge/core";

export interface CreateImportedSourceProjectInput {
  name: string;
  source: string;
  kind: Exclude<SourceArtifactKind, "graphforge-json">;
  origin: SourceArtifactOrigin;
  createdAt: string;
}

export interface CreateImportedSourceDocumentInput extends CreateImportedSourceProjectInput {
  assetPath?: string;
}

export async function createImportedSourceProject(input: CreateImportedSourceProjectInput): Promise<OgProject> {
  const sourceArtifact: GraphForgeSourceArtifact = {
    kind: input.kind,
    origin: input.origin,
    path: input.source,
    createdAt: input.createdAt
  };
  const project = createDefaultProject({
    name: input.name,
    strategy: "common",
    generationMode: input.kind === "image" ? "pure-image" : "template",
    sourceArtifacts: [sourceArtifact],
    title: input.name,
    subtitle: "Generated by the coding agent and opened for Studio finalization."
  });

  const sourceUrl = input.kind === "svg" || input.kind === "image" ? await toBrowserSafeSource(input.source, input.kind) : input.source;
  const sourceLayer =
    input.kind === "html"
      ? {
          id: "imported-html-source",
          kind: "screenshot" as const,
          name: "Imported HTML Source",
          x: 760,
          y: 112,
          width: 340,
          height: 360,
          rotation: 0,
          opacity: 1,
          locked: false,
          hidden: false,
          src: "graphforge://html-source",
          fit: "contain" as const,
          borderRadius: 8,
          effects: { shadow: true, glow: false, blur: 0 }
        }
      : {
          id: `imported-${input.kind}-source`,
          kind: "image" as const,
          name: input.kind === "svg" ? "Imported SVG Source" : "Imported Image Source",
          x: 0,
          y: 0,
          width: 1200,
          height: 630,
          rotation: 0,
          opacity: 1,
          locked: false,
          hidden: false,
          src: sourceUrl,
          fit: "contain" as const,
          borderRadius: 0,
          effects: { shadow: false, glow: false, blur: 0 }
        };

  return {
    ...project,
    canvas: { ...project.canvas, background: "#111315" },
    layers: [
      {
        id: "background",
        kind: "background",
        name: "Background",
        x: 0,
        y: 0,
        width: 1200,
        height: 630,
        rotation: 0,
        opacity: 1,
        locked: true,
        hidden: false,
        fill: "#111315",
        radius: 0,
        effects: { shadow: false, glow: false, blur: 0 }
      },
      sourceLayer
    ],
    updatedAt: input.createdAt
  };
}

export async function createImportedSourceDocument(input: CreateImportedSourceDocumentInput): Promise<StudioDocumentPackage> {
  const assetBytes = await readFile(input.source);
  const assetPath = input.assetPath ?? createAssetPath(input.source);
  const sourceArtifact: GraphForgeSourceArtifact = {
    kind: input.kind,
    origin: input.origin,
    path: assetPath,
    createdAt: input.createdAt
  };
  const project = createDefaultProject({
    name: input.name,
    strategy: "common",
    generationMode: "pure-image",
    sourceArtifacts: [sourceArtifact],
    title: input.name,
    subtitle: "Generated by the coding agent and opened for Studio finalization."
  });
  const sourceLayer =
    input.kind === "html"
      ? {
          id: "imported-html-source",
          kind: "screenshot" as const,
          name: "Imported HTML Source",
          x: 0,
          y: 0,
          width: 1200,
          height: 630,
          rotation: 0,
          opacity: 1,
          locked: false,
          hidden: false,
          src: assetPath,
          assetPath,
          fit: "contain" as const,
          borderRadius: 0,
          effects: { shadow: false, glow: false, blur: 0 }
        }
      : {
          id: `imported-${input.kind}-source`,
          kind: "image" as const,
          name: input.kind === "svg" ? "Imported SVG Source" : "Imported Image Source",
          x: 0,
          y: 0,
          width: 1200,
          height: 630,
          rotation: 0,
          opacity: 1,
          locked: false,
          hidden: false,
          src: assetPath,
          assetPath,
          fit: "contain" as const,
          borderRadius: 0,
          effects: { shadow: false, glow: false, blur: 0 }
        };

  return {
    manifest: {
      format: "og-studio-document",
      formatVersion: "1.0",
      projectId: project.projectId,
      name: project.name,
      document: "document.json",
      assets: [],
      previews: [],
      createdAt: project.createdAt,
      updatedAt: input.createdAt
    },
    project: {
      ...project,
      canvas: { ...project.canvas, background: "#111315" },
      layers: [
        {
          id: "background",
          kind: "background",
          name: "Background",
          x: 0,
          y: 0,
          width: 1200,
          height: 630,
          rotation: 0,
          opacity: 1,
          locked: true,
          hidden: false,
          fill: "#111315",
          radius: 0,
          effects: { shadow: false, glow: false, blur: 0 }
        },
        sourceLayer
      ],
      updatedAt: input.createdAt
    },
    assets: { [assetPath]: assetBytes },
    previews: {}
  };
}

async function toBrowserSafeSource(source: string, kind: "svg" | "image"): Promise<string> {
  if (source.startsWith("data:") || source.startsWith("http://") || source.startsWith("https://")) return source;
  const buffer = await readFile(source);
  const mime = kind === "svg" ? "image/svg+xml" : mimeFromExtension(source);
  return `data:${mime};base64,${buffer.toString("base64")}`;
}

function mimeFromExtension(source: string): string {
  const extension = extname(source).toLowerCase();
  if (extension === ".jpg" || extension === ".jpeg") return "image/jpeg";
  if (extension === ".webp") return "image/webp";
  if (extension === ".svg") return "image/svg+xml";
  return "image/png";
}
